# Generated by Django 5.1.7 on 2025-04-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_password_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
