# Generated by Django 5.1.7 on 2025-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_proof', models.FileField(upload_to='documents/')),
                ('land_image', models.ImageField(upload_to='images/')),
                ('water_source', models.CharField(max_length=255)),
                ('electricity_connection', models.CharField(max_length=255)),
                ('land_type', models.CharField(max_length=255)),
                ('total_area', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
