# Generated by Django 5.1.7 on 2025-04-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_property_ownership_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='land_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ownership_proof',
        ),
    ]
