# Generated by Django 5.1.7 on 2025-04-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_property_land_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
