# Generated by Django 5.1.7 on 2025-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_property_land_image_property_ownership_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_proof',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
