# Generated by Django 5.1.7 on 2025-04-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_property_land_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ownership_proof',
        ),
    ]
