# Generated by Django 5.1.7 on 2025-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_property_ownership_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
