# Generated by Django 5.1.7 on 2025-04-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='country',
            new_name='state',
        ),
    ]
