# Generated by Django 5.1.7 on 2025-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_country_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
