# Generated by Django 5.1.7 on 2025-04-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
