# Generated by Django 5.1.7 on 2025-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_proof',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
