# Generated by Django 5.1.7 on 2025-04-30 06:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_property_land_owner_photo_property_ownership_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='land_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_owner_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='land_owner_photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ownership_proof'),
        ),
    ]
