# Generated by Django 5.1.7 on 2025-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_property_land_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_image',
            field=models.ImageField(default='img_3.jpg', upload_to='land_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='land_owner_photo',
            field=models.ImageField(default='person_4-min.jpg', upload_to='owner_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_proof',
            field=models.ImageField(default='img_8.jpg', upload_to='ownership_proofs/'),
            preserve_default=False,
        ),
    ]
