# Generated by Django 5.1.7 on 2025-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_userprofile_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_icon.jpeg', upload_to='profile_pics/'),
        ),
    ]
