# Generated by Django 5.1.7 on 2025-05-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_propertymessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyMessage',
        ),
    ]
