# Generated by Django 5.1.7 on 2025-05-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_wishlist_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_images', to='members.property')),
            ],
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
