# Generated by Django 5.1.7 on 2025-05-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_landimage_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='land_image',
        ),
    ]
