# Generated by Django 5.1.7 on 2025-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_remove_property_land_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_agent_application_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='was_agent_application_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
