# Generated by Django 5.1.7 on 2025-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_visitrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
